include detekt warnings in the checks

diff --git a/.github/workflows/detekt.yml b/.github/workflows/detekt.yml
--- a/.github/workflows/detekt.yml
+++ b/.github/workflows/detekt.yml
@@ -5,27 +5,25 @@ on: [ pull_request ]
 jobs:
   detekt:
     runs-on: ubuntu-latest
-      env:
-        GRADLE_OPTS: -Dorg.gradle.daemon=false
-      steps:
-        - name: Checkout Repo
-          uses: actions/checkout@v3
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v3
 
-        - name: Setup Java
-          uses: actions/setup-java@v3
-          with:
-            java-version: 11
+      - name: Setup Java
+        uses: actions/setup-java@v3
+        with:
+          java-version: 11
 
-        - name: Run detekt
-          run: ./gradlew detekt
+      - name: Run detekt
+        run: ./gradlew detekt
 
-        - name: Merge modules reports in one report
-            run:  ./gradlew detekt reportMerge
+      - name: Merge modules reports in one report
+          run:  ./gradlew detekt reportMerge
 
-        # Make sure we always run this upload task,
-        # because the previous step may fail if there are findings.
-        - name: Upload SARIF to Github using the upload-sarif action
-          uses: github/codeql-action/upload-sarif@v1
-          if: success() || failure()
-          with:
-            sarif_file: build/reports/detekt/merge.sarif
+      # Make sure we always run this upload task,
+      # because the previous step may fail if there are findings.
+      - name: Upload SARIF to Github using the upload-sarif action
+        uses: github/codeql-action/upload-sarif@v1
+        if: success() || failure()
+        with:
+          sarif_file: build/reports/detekt/merge.sarif
