Implement the recently viewed section (#19)
implement recently viewed section and added testing

diff --git a/.github/workflows/detekt.yml b/.github/workflows/detekt.yml
--- a/.github/workflows/detekt.yml
+++ b/.github/workflows/detekt.yml
@@ -4,11 +4,11 @@ on: [ pull_request ]
 
 jobs:
   detekt:
-
     runs-on: ubuntu-latest
-
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout Repo
+        uses: actions/checkout@v3
+
       - name: set up JDK 11
         uses: actions/setup-java@v3
         with:
@@ -18,5 +18,20 @@ jobs:
 
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
-      - name: Run Detekt Code Analysis
+
+      - name: Run detekt
         run: ./gradlew detekt
+
+      - name: Merge modules reports in one report
+        run:  ./gradlew detekt reportMerge
+
+      - name: Replace Detekt absolute paths with relative ones
+        run:  python ./config/detekt/fix_location.py ${{ github.workspace }}
+
+      # Make sure we always run this upload task,
+      # because the previous step may fail if there are findings.
+      - name: Upload SARIF to Github using the upload-sarif action
+        uses: github/codeql-action/upload-sarif@v1
+        if: success() || failure()
+        with:
+          sarif_file: build/reports/detekt/merge.sarif
